/* Atividade_BD_22-03_logico: */

CREATE TABLE ALUNO (
    ALU_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    ALU_MATRICULA CHAR(13) NOT NULL,
    ALU_ENDERECO VARCHAR(100) NULL,
    ALU_NOME VARCHAR(100) NOT NULL,
    ALU_TELEFONE NUMERIC(10,2) NOT NULL,
    ALU_CPF VARCHAR(11) NOT NULL
);

CREATE TABLE TREINO (
    TRE_PROFESSOR VARCHAR NULL,
    TRE_NOME VARCHAR(100) NOT NULL,
    TRE_MODALIDADE VARCHAR(100) NOT NULL,
    TRE_CODIGO SERIAL PRIMARY KEY UNIQUE,
    TRE_MATRICULA CHAR(13) NOT NULL,
    TRE_SERIES NUMERIC(10,2) NOT NULL,
    TRE_CARGA NUMERIC(10,2) NOT NULL,
    TRE_REPETICOES NUMERIC(10,2) NOT NULL,
    TRE_APARELHOS VARCHAR(100)
);

CREATE TABLE MENSALIDADE (
    MEN_MATRICULA CHAR(13) NOT NULL,
    MEN_DATA DATE NOT NULL,
    MEN_NOME VARCHAR(100) NOT NULL,
    MEN_CODIGO SERIAL PRIMARY KEY UNIQUE
);

CREATE TABLE PROFESSOR (
    PRO_NOME VARCHAR(100) NOT NULL,
    PRO_MODALIDADE VARCHAR(100) NOT NULL,
    PRO_CODIGO SERIAL PRIMARY KEY UNIQUE,
    PRO_TELEFONE NUMERIC(11) NOT NULL,,
    PRO_CPF VARCHAR(13) NOT NULL,
    PRO_ENDERECO VARCHAR(100) NOT NULL,
    TRE_CODIGO INTEGER
);

CREATE TABLE MODALIDADES (
    MOD_JUMP CHAR,
    MOD_MUSCULACAO CHAR,
    MOD_CODIGO SERIAL PRIMARY KEY UNIQUE,
    MOD_STEP CHAR,
    CHECK(MOD_JUMP = "SIM" OR MOD_JUMP ="NAO"),
    CHECK(MOD_STEP ="SIM" OR MOD_JUMP ="NAO"),
    CHECK(MOD_MUSCULACAO ="SIM" OR MOD_MUSCULACAO ="NAO")
);

CREATE TABLE AVALIACAO (
    AVA_CODIGO SERIAL PRIMARY KEY UNIQUE,
    AVA_NOME VARCHAR(100) NOT NULL,
    AVA_DATA DATE NOT NULL,
    AVA_MATRICULA CHAR(13) NOT NULL,
    AVA_GORDURA NUMERIC(10,2) NOT NULL,
    AVA_ALTURA DECIMAL(10,2) NOT NULL,
    AVA_PESO DECIMAL(10,2) NOT NULL,
);

CREATE TABLE R_1 (
    MOD_CODIGO INTEGER,
    ALU_CODIGO INTEGER,
    ALU_MOD_NOME VARCHAR(100) NOT NULL,
    ALU_MOD_MATRICULA CHAR(13) NOT NULL,
    PRIMARY KEY (MOD_CODIGO, ALU_CODIGO)
);

CREATE TABLE R_2 (
    MOD_CODIGO INTEGER,
    PRO_CODIGO INTEGER,
    MOD_PRO_NOME VARCHAR(100) NOT NULL,
    MOD_PRO_MATRICULA CHAR(13) NOT NULL,
    PRIMARY KEY (MOD_CODIGO, PRO_CODIGO)
);

CREATE TABLE R_3 (
    MEN_CODIGO INTEGER,
    ALU_CODIGO INTEGER,
    PRIMARY KEY (MEN_CODIGO, ALU_CODIGO)
);

CREATE TABLE R_4 (
    AVA_CODIGO INTEGER,
    ALU_CODIGO INTEGER,
    AVA_ALU_MATRICULA CHAR(13) NOT NULL,
    AVA_ALU_DATA DATE NOT NULL,
    AVA_ALU_NOME VARCHAR(100) NOT NULL,
    PRIMARY KEY (AVA_CODIGO, ALU_CODIGO)
);

CREATE TABLE CTT_EMERGENCIA (
    CTT_CODIGO SERIAL PRIMARY KEY UNIQUE,
    CTT_NOME VARCHAR(100) NOT NULL,
    CTT_TELEFONE VARCHAR(11) NOT NULL,
    CTT_PARENTESCO VARCHAR(100) NOT NULL
);

ALTER TABLE PROFESSOR ADD CONSTRAINT PROFESSOR_2
    FOREIGN KEY (TRE_CODIGO)
    REFERENCES TREINO (TRE_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE R_1 ADD CONSTRAINT R_1_1
    FOREIGN KEY (MOD_CODIGO)
    REFERENCES MODALIDADES (MOD_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE R_1 ADD CONSTRAINT R_1_2
    FOREIGN KEY (ALU_CODIGO)
    REFERENCES ALUNO (ALU_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE R_2 ADD CONSTRAINT R_2_1
    FOREIGN KEY (MOD_CODIGO)
    REFERENCES MODALIDADES (MOD_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE R_2 ADD CONSTRAINT R_2_2
    FOREIGN KEY (PRO_CODIGO)
    REFERENCES PROFESSOR (PRO_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE R_3 ADD CONSTRAINT R_3_1
    FOREIGN KEY (MEN_CODIGO)
    REFERENCES MENSALIDADE (MEN_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE R_3 ADD CONSTRAINT R_3_2
    FOREIGN KEY (ALU_CODIGO)
    REFERENCES ALUNO (ALU_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE R_4 ADD CONSTRAINT R_4_1
    FOREIGN KEY (AVA_CODIGO)
    REFERENCES AVALIACAO (AVA_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE R_4 ADD CONSTRAINT R_4_2
    FOREIGN KEY (ALU_CODIGO)
    REFERENCES ALUNO (ALU_CODIGO)
    ON DELETE RESTRICT;