/* Lógico_ACADEMIA_BD: */

CREATE TABLE ALUNO (
    ALU_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    ALU_MATRICULA VARCHAR,
    ALU_ENDERECO VARCHAR(100) NULL,
    ALU_NOME VARCHAR(100) NOT NULL,
    ALU_TELEFONE VARCHAR(11) NOT NULL,
    ALU_PARENTESCO VARCHAR(100) NOT NULL,
    ALU_CPF VARCHAR(13) NOT NULL,
    FK_MEN_CODIGO INTEGER NOT NULL,
    FK_MOD_CODIGO INTEGER NOT NULL
);

CREATE TABLE TREINO (
    TRE_PROFESSOR VARCHAR(100) NOT NULL,
    TRE_NOME VARCHAR(100) NOT NULL,
    TRE_MODALIDADE VARCHAR(),
    TRE_CODIGO SERIAL PRIMARY KEY UNIQUE,
    TRE_MATRICULA VARCHAR NOT NULL,
    TRE_APARELHOS VARCHAR(100) NOT NULL,
    TRE_REPETICOES INTEGER NOT NULL,
    TRE_SERIES INTEGER NOT NULL,
    TRE_CARGA NUMERIC NOT NULL
);

CREATE TABLE MENSALIDADE (
    MEN_MATRICULA VARCHAR NOT NULL,
    MEN_VALOR NUMERIC(15,2) NOT NULL,
    MEN_ACRESCIMO NUMERIC(15,2) NOT NULL,
    MEN_DATA DATE NOT NULL,
    MEN_NOME VARCHAR(100) NOT NULL,
    MEN_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    MEN_QND_PAGOU DATE NOT NULL,
    MEN_QND_VENCEU DATE NOT NULL
);

CREATE TABLE PROFESSOR (
    PRO_NOME VARCHAR(100) NOT NULL,
    PRO_MODALIDADE VARCHAR NOT NULL,
    PRO_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    PRO_TELEFONE VARCHAR(11) NOT NULL,
    PRO_CPF VARCHAR(13) NOT NULL,
    PRO_ENDERECO VARCHAR(100) NULL,
    FK_TRE_CODIGO INTEGER NOT NULL,
    FK_AVA_CODIGO INTEGER NOT NULL
);

CREATE TABLE MODALIDADES (
    MOD_NOME VARCHAR(100) NOT NULL,
    MOD_DESCRICAO VARCHAR(200) NOT NULL,
    MOD_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL, 
    MOD_REQUISITO VARCHAR(100) NOT NULL,
    MOD_VALOR NUMERIC(15,2) NOT NULL,
    FK_PRO_CODIGO INTEGER NOT NULL
);

CREATE TABLE AVALIACAO (
    AVA_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    AVA_NOME VARCHAR(100) NOT NULL,
    AVA_DATA DATE NOT NULL,
    AVA_MATRICULA VARCHAR NOT NULL,
    AVA_ALTURA NUMERIC(15,2) NOT NULL,
    AVA_GORDURA NUMERIC(15,2) NOT NULL,
    AVA_PESO NUMERIC(15,2) NOT NULL,
    FK_ALU_CODIGO INTEGER NOT NULL,
    AVA_ALU_MATRICULA INTEGER NOT NULL,
    AVA_ALU_DATA DATE NOT NULL,
    AVA_ALU_NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CTT_EMERGENCIA (
    CTT_NOME VARCHAR(100) NOT NULL,
    CTT_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    CTT_PARENTESCO VARCHAR(100) NOT NULL,
    CTT_TELEFONE VARCHAR(11) NOT NULL,
    FK_ALU_CODIGO INTEGER NOT NULL
);

CREATE TABLE MATRICULA (
    MAT_VALOR NUMERIC(15,2) NOT NULL,
    MAT_DT_INI DATE NOT NULL,
    MAT_DT_FIM DATE NOT NULL,
    MAT_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    FK_ALU_CODIGO INTEGER NOT NULL,
    FK_MOD_CODIGO INTEGER NOT NULL
);
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_2
    FOREIGN KEY (FK_MEN_CODIGO)
    REFERENCES MENSALIDADE (MEN_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE ALUNO ADD CONSTRAINT FK_ALUNO_3
    FOREIGN KEY (FK_MOD_CODIGO)
    REFERENCES MODALIDADES (MOD_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PROFESSOR ADD CONSTRAINT FK_PROFESSOR_2
    FOREIGN KEY (FK_TRE_CODIGO)
    REFERENCES TREINO (TRE_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PROFESSOR ADD CONSTRAINT FK_PROFESSOR_3
    FOREIGN KEY (FK_AVA_CODIGO)
    REFERENCES AVALIACAO (AVA_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE MODALIDADES ADD CONSTRAINT FK_MODALIDADES_2
    FOREIGN KEY (FK_PRO_CODIGO)
    REFERENCES PROFESSOR (PRO_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_2
    FOREIGN KEY (FK_ALU_CODIGO)
    REFERENCES ALUNO (ALU_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE CTT_EMERGENCIA ADD CONSTRAINT FK_CTT_EMERGENCIA_2
    FOREIGN KEY (FK_ALU_CODIGO)
    REFERENCES ALUNO (ALU_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_2
    FOREIGN KEY (FK_ALU_CODIGO)
    REFERENCES ALUNO (ALU_CODIGO)
    ON DELETE CASCADE;
 
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_3
    FOREIGN KEY (FK_MOD_CODIGO)
    REFERENCES MODALIDADES (MOD_CODIGO)
    ON DELETE RESTRICT;