/* logico_academia_adilso: */

CREATE DOMAIN dm_dinheiro NUMERIC(15,2)

CREATE TABLE MODALIDADES (
    mod_nome VARCHAR(100) NOT NULL,
    mod_descricao VARCHAR(100) NOT NULL,
    mod_restricao VARCHAR (100) NOT NULL,
    mod_valor dm_dinheiro NOT NULL,
    mod_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    FK_PESSOA_codigo INTEGER
);

CREATE TABLE PESSOA (
    dad_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    dad_nome VARCHAR(100) NOT NULL,
    dad_idade VARCHAR (100) NOT NULL,
    dad_cpf VARCHAR (11)NOT NULL,
    dad_matricula VARCHAR,
    dad_endereco VARCHAR,
    pes_tipo CHAR,
    FK_CTT_EMERGENCIA_ctt_codigo INTEGER
);

CREATE TABLE CTT_EMERGENCIA (
    ctt_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    ctt_nome VARCHAR(100) NOT NULL,
    ctt_telefone VARCHAR(11) NOT NULL,
    ctt_parenstesco VARCHAR(100) NOT NULL,
    ctt_email VARCHAR(100) NULL
);

CREATE TABLE AVALIACAO (
    ava_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    ava_per_gordura NUMERIC (15,2) NOT NULL,
    ava_altura INTEGER NOT NULL,
    ava_peso NUMERIC (15,2) NOT NULL,
    ava_data DATE NOT NULL,
    ava_dt_validade DATE NOT NULL,
    FK_PESSOA_dad_codigo INTEGER,
    FK_PESSOA_dad_codigo_ INTEGER
);

CREATE TABLE PROG_DE_TREINO (
    pro_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    pro_dt_ini DATE NOT NULL,
    pro_dt_fim DATE NULL,
    pro_repeticao INTEGER NULL,
    pro_peso NUMERIC(15,2) NULL,
    pro_tempo TIME NULL,
    pro_qtd INTEGER NULL,
    pro_objetivo VARCHAR (100)NOT NULL,
    FK_MATRICULA_mat_codigo INTEGER,
    FK_APARELHO_apa_codigo INTEGER
);
CREATE TABLE MATRICULA (
    mat_dt_fim DATE NULL,
    mat_valor dm_dinheiro NOT NULL,
    mat_dt_ini DATE NOT NULL,
    mat_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    FK_MODALIDADES_mod_codigo INTEGER,
    FK_PESSOA_dad_codigo INTEGER
);

CREATE TABLE MENSALIDADE (
    men_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    men_valor dm_dinheiro NOT NULL,
    men_dt_pagou DATE NULL,
    men_mes INTEGER NOT NULL,
    men_dt_vence DATE NOT NULL,
    men_acrescimo NUMERIC (15,2) NULL,
    FK_MATRICULA_mat_codigo INTEGER
);

CREATE TABLE APARELHO (
    apa_codigo SERIAL NOT NULL PRIMARY KEY UNIQUE,
    apa_orientacoes VARCHAR (100) NOT NULL,
    apa_limitacoes VARCHAR(100) NOT NULL,
    apa_nome VARCHAR (100) NOT NULL
);


ALTER TABLE PESSOA ADD CHECK (pes_tipo="P" OR pes_tipo="A");

ALTER TABLE PROG_DE_TREINO DROP pro_repeticao;
ALTER TABLE PROG_DE_TREINO ADD pro_repeticao type INTEGER NOT NULL;

ALTER TABLE AVALIACAO DROP FK_PESSOA_dad_codigo
ALTER TABLE AVALIACAO DROP FK_PESSOA_dad_codigo_
ALTER TABLE AVALIACAO ADD CONSTRAINT AVALIACAO

ALTER TABLE MODALIDADES ADD CONSTRAINT FK_MODALIDADES_2
    FOREIGN KEY (FK_dad_codigo)
    REFERENCES PESSOA (dad_codigo)
    ON DELETE CASCADE;

ALTER TABLE PESSOA ADD CONSTRAINT FK_PESSOA_2
    FOREIGN KEY (FK_CTT_ctt_codigo)
    REFERENCES CTT_EMERGENCIA (ctt_codigo)
    ON DELETE CASCADE;
 
ALTER TABLE AVALIACAO ADD CONSTRAINT FK_AVALIACAO_2
    FOREIGN KEY (FK_PESSOA_dad_codigo, FK_PESSOA_dad_codigo_)
    REFERENCES PESSOA (dad_codigo, dad_codigo)
    ON DELETE CASCADE;
 
ALTER TABLE PROG_DE_TREINO ADD CONSTRAINT FK_PROG_DE_TREINO_2
    FOREIGN KEY (FK_MATRICULA_mat_codigo)
    REFERENCES MATRICULA (mat_codigo)
    ON DELETE RESTRICT;
 
ALTER TABLE PROG_DE_TREINO ADD CONSTRAINT FK_PROG_DE_TREINO_3
    FOREIGN KEY (FK_APARELHO_apa_codigo)
    REFERENCES APARELHO (apa_codigo)
    ON DELETE SET NULL;
 
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_2
    FOREIGN KEY (FK_MODALIDADES_mod_codigo)
    REFERENCES MODALIDADES (mod_codigo)
    ON DELETE CASCADE;
 
ALTER TABLE MATRICULA ADD CONSTRAINT FK_MATRICULA_3
    FOREIGN KEY (FK_PESSOA_dad_codigo)
    REFERENCES PESSOA (dad_codigo)
    ON DELETE CASCADE;
 
ALTER TABLE MENSALIDADE ADD CONSTRAINT FK_MENSALIDADE_2
    FOREIGN KEY (FK_MATRICULA_mat_codigo)
    REFERENCES MATRICULA (mat_codigo)
    ON DELETE CASCADE;