/* BD_Trabalho_1_Rafael_e_Eduardo_MER_LÓGICO: */

CREATE TABLE ATLETAS (
    ATLE_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    ATLE_NOME VARCHAR(100) NOT NULL,
    ATLE_NUM_INDIVIDUAL INTEGER NOT NULL,
    ATLE_PROFISSIONAL CHAR(1) NOT NULL,
    ATLE_AMADOR CHAR(1) NOT NULL
);
ALTER TABLE ATLETAS ADD CHECK(ATLE_AMADOR='S' OR ATLE_AMADOR='N')
ALTER TABLE ATLETAS ADD CHECK(ATLE_PROFISSIONAL='S' OR ATLE_PROFISSIONAL='N')

CREATE TABLE CADASTRO (
    CADA_NOME VARCHAR(100) NOT NULL,
    CADA_CPF VARCHAR(13) NOT NULL,
    CADA_IDADE INTEGER NOT NULL,
    CADA_EMAIL VARCHAR(100) NOT NULL,
    CADA_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    CADA_TELEFONE VARCHAR(11) NOT NULL,
    CADA_NUM_EMERGENCIA VARCHAR(11) NOT NULL,
    CADA_ENDERECO VARCHAR(100) NULL,
    FK_ATLE_CODIGO INTEGER NOT NULL
);

CREATE TABLE CATEGORIA (
    CATE_NOME VARCHAR(100) NOT NULL,
    CATE_EQUIP_UTILIZADO VARCHAR(100) NOT NULL,
    CATE_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    FK_INSC_CODIGO INTEGER NOT NULL
);

CREATE TABLE DESEMPENHO (
    DESE_CODIGO SERIAL UNIQUE NOT NULL,
    DESE_TEMPO TIME NOT NULL,
    DESE_POSICAO INTEGER NOT NULL,
    DESE_TEMPO_PROVA TIME NOT NULL,
    DESE_DATA_CHEGADA DATE NOT NULL,
    DESE_DATA_LARGADA DATE NOT NULL,
    DESE_HORA_LARGADA TIME NOT NULL,
    DESE_HORA_CHEGADA TIME NOT NULL,
    FK_ATLE_CODIGO INTEGER NOT NULL,
    FK_RAN_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (DESE_CODIGO, FK_ATLE_CODIGO, FK_RAN_CODIGO)
);

CREATE TABLE PENALIDADES (
    PENA_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    PENA_INFRACAO VARCHAR(100) NOT NULL,
    PENA_TEMPO_EXCEDIDO TIME NOT NULL,
    PENA_TEMPO_ACRESCIDO TIME NOT NULL,
    FK_DESE_CODIGO INTEGER NOT NULL
);

CREATE TABLE COMPETICAO (
    COMP_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    COMP_ORG_AUX VARCHAR(100) NOT NULL,
    COMP_EQUIPE_ORGANIZADORA VARCHAR(100) NOT NULL,
    COMP_PATROCINIOS VARCHAR(100) NOT NULL,
    FK_TEMP_CODIGO INTEGER NOT NULL
);

CREATE TABLE TEMPORADA (
    TEMP_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    TEMP_ETAPA VARCHAR(100) NOT NULL,
    TEMP_DATAS DATE NOT NULL,
    TEMP_INSCRITOS INTEGER NOT NULL,
    TEMP_PISTAS VARCHAR(100) NOT NULL
);

CREATE TABLE INSCRICAO (
    INSC_EQUIPE_DO_ATLETA VARCHAR(100) NOT NULL,
    INSC_CODIGO SERIAL PRIMARY KEY NOT NULL,
    INSC_NUM_INCRICAO INTEGER NOT NULL,
    INSC_EVENTO VARCHAR(100) NOT NULL,
    FK_CADA_CODIGO INTEGER NOT NULL,
    UNIQUE (INSC_CODIGO, INSC_NUM_INCRICAO)
);

CREATE TABLE ETAPA (
    ETA_CODIGO SERIAL PRIMARY KEY UNIQUE NOT NULL,
    ETA_DATA DATE NOT NULL,
    ETA_CIDADE VARCHAR(100) NOT NULL,
    ETA_ESTADO VARCHAR(100) NOT NULL,
    ETA_TERRENO VARCHAR(100) NOT NULL,
    FK_TEMP_CODIGO INTEGER NOT NULL
);

CREATE TABLE RANQUEAMENTO (
    RAN_CLASSIFICACAO INTEGER NOT NULL,
    RAN_CODIGO SERIAL PRIMARY KEY NOT NULL,
    RAN_RESULTADOS_TEMPO TIME NOT NULL,
    FK_TEMP_CODIGO INTEGER NOT NULL
);

CREATE TABLE COMP_ATLE (
    FK_ATLE_CODIGO INTEGER NOT NULL,
    FK_COMP_CODIGO INTEGER NOT NULL,
    COMP_ATLE_QTD_EQUIPES INTEGER NOT NULL,
    COMP_ATLE_NUM_ATLETAS INTEGER NOT NULL,
    PRIMARY KEY (FK_COMP_CODIGO, FK_ATLE_CODIGO)
);

CREATE TABLE ATLE_CATE (
    FK_ATLE_CODIGO INTEGER NOT NULL,
    FK_CATE_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (FK_ATLE_CODIGO, FK_CATE_CODIGO)
);
 
ALTER TABLE CADASTRO ADD CONSTRAINT FK_CADASTRO_2
    FOREIGN KEY (FK_ATLE_CODIGO)
    REFERENCES ATLETAS (ATLE_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE CATEGORIA ADD CONSTRAINT FK_CATEGORIA_2
    FOREIGN KEY (FK_INSC_CODIGO)
    REFERENCES INSCRICAO (INSC_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE DESEMPENHO ADD CONSTRAINT FK_DESEMPENHO_2
    FOREIGN KEY (FK_ATLE_CODIGO)
    REFERENCES ATLETAS (ATLE_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE DESEMPENHO ADD CONSTRAINT FK_DESEMPENHO_3
    FOREIGN KEY (FK_RAN_CODIGO)
    REFERENCES RANQUEAMENTO (RAN_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE PENALIDADES ADD CONSTRAINT FK_PENALIDADES_2
    FOREIGN KEY (FK_DESE_CODIGO)
    REFERENCES DESEMPENHO (DESE_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE COMPETICAO ADD CONSTRAINT FK_COMPETICAO_2
    FOREIGN KEY (FK_TEMP_CODIGO)
    REFERENCES TEMPORADA (TEMP_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE INSCRICAO ADD CONSTRAINT FK_INSCRICAO_2
    FOREIGN KEY (FK_CADA_CODIGO)
    REFERENCES CADASTRO (CADA_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE ETAPA ADD CONSTRAINT FK_ETAPA_2
    FOREIGN KEY (FK_TEMP_CODIGO)
    REFERENCES TEMPORADA (TEMP_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE RANQUEAMENTO ADD CONSTRAINT FK_RANQUEAMENTO_2
    FOREIGN KEY (FK_TEMP_CODIGO)
    REFERENCES TEMPORADA (TEMP_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE COMP_ATLE ADD CONSTRAINT FK_COMP_ATLE_1
    FOREIGN KEY (FK_ATLE_CODIGO)
    REFERENCES ATLETAS (ATLE_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE COMP_ATLE ADD CONSTRAINT FK_COMP_ATLE_2
    FOREIGN KEY (FK_COMP_CODIGO)
    REFERENCES COMPETICAO (COMP_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE ATLE_CATE ADD CONSTRAINT FK_ATLE_CATE_1
    FOREIGN KEY (FK_ATLE_CODIGO)
    REFERENCES ATLETAS (ATLE_CODIGO)
    ON DELETE RESTRICT;
 
ALTER TABLE ATLE_CATE ADD CONSTRAINT FK_ATLE_CATE_2
    FOREIGN KEY (FK_CATE_CODIGO)
    REFERENCES CATEGORIA (CATE_CODIGO)
    ON DELETE RESTRICT;